### ISSUE TITLE
Option to remove the text search

### ISSUE THREAD

**Issue by melnele** [AdevintaSpain/Leku#187]
Is it possible to remove the text search or customize it with other providers

**Comment by ferranpons** [comment]
Hi @melnele !

Please could you elaborate a bit more what you are requesting? With an example?

Because I'm not sure If I understood well what you requested.

Many thanks in advance!

**Comment by ferranpons** [comment]
This feature is already done on the latest version. Check out: `.withSearchBarHidden()`
