### ISSUE TITLE
offline support for Gps location selection

### ISSUE THREAD

**Issue by vicky-tech** [AdevintaSpain/Leku#188]
**Describe the bug**
App crash when we change location and select (offline)

**To Reproduce**
select different location from default location then click on done

**Expected behavior**
app should not crash
**Info Required**
- Which version of the library do you actually use?

- Do you have the localization permission granted?

- Are you sending parameters to the activity through the bundle?

- Android monitor shows any log related to the library when the error is shown?

- Any other thing that could help me to reproduce the error?

**Screenshots**

**Smartphone:**
 - Device: All

**Additional context**

**Comment by ferranpons** [comment]
Hi @desigame !

Please could you send to us more info about your crash?

**Info Required**
- Which version of the library do you actually use?

- Do you have the localization permission granted?

- Are you sending parameters to the activity through the bundle?

- Android monitor shows any log related to the library when the error is shown?

- Any other thing that could help me to reproduce the error?

- Stacktrace of the error?


Many thanks!

**Comment by desigame** [comment]
Just switch off mobile data/wifi and open the map location activity
Crash happen

**Comment by ferranpons** [comment]
@desigame I'm looking into it. I'll publish a fix as soon as possible. Thanks for reporting it.

**Comment by ferranpons** [comment]
@desigame please could you confirm me that this issues is solved? Many thanks

**Comment by desigame** [comment]
Yes
