### ISSUE TITLE
Unable to resolve by gradle v5.1.1

### ISSUE THREAD

**Issue by BilalSiddiqui** [AdevintaSpain/Leku#208]
**Describe the bug**
Version 5.1.1 is not resolving and not even 5.1.0 but able to resolve 5.0.0

**To Reproduce**
Use implementation 'com.schibstedspain.android:leku:5.1.1'

**Comment by ferranpons** [comment]
@BilalSiddiqui I'm looking into it. Sorry for the inconvenience.

Thanks for reporting it.

**Comment by ferranpons** [comment]
@BilalSiddiqui please could you try again with version 5.1.1? It should be ok now.

**Comment by BilalSiddiqui** [comment]
Now getting couple of errors. 

error: resource string/leku_title_activity_location_picker (aka com.targetofs.qaissocial:string/leku_title_activity_location_picker) not found.
error: resource xml/leku_searchable (aka com.targetofs.qaissocial:xml/leku_searchable) not found.

**Comment by ferranpons** [comment]
![oh come on](https://media.giphy.com/media/U4VXRfcY3zxTi/giphy.gif)

**Comment by Midhilaj** [comment]
@ferranpons why did you ignore my issue
 https://github.com/SchibstedSpain/Leku/issues/206

**Comment by Midhilaj** [comment]
@ferranpons   I'm sorry if I've hurt you knowingly or unknowingly

**Comment by ferranpons** [comment]
@Midhilaj don't worry you didn't hurt me in any way. I just wanted to say you to have a some patience. 😄

**Comment by ferranpons** [comment]
@Midhilaj I've re-uploaded the aar but I'm not sure if it's working correctly

**Comment by VinceGee** [comment]
Yeah I have the same issue with: `implementation 'com.schibstedspain.android:leku:5.1.1'`
Im getting this error: "error: cannot find symbol variable LocationPickerActivity"
 but if i revert to `implementation 'com.schibstedspain.android:leku:3.2.0'` it works fine

**Comment by ferranpons** [comment]
New version 5.1.3 should solve this issue. Please use the latest instead of 5.1.1.

Sorry for the inconvenience
