### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by RegisSaffi** [AdevintaSpain/Leku#211]
I am having trouble with this library, i used it in my previous project and it worked perfectly.
But in my current project,  when i open location intent, it is lagging and cause not responding error, this is being when internet connection is on, when i switch off internet connection, it work well. Can you help me what's the cause of this?

**Comment by ferranpons** [comment]
Hi @RegisSaffi !

Sorry for replying late. Please could you send me more info about how are you using the library?

- Which version of play services are you using?
- Version of the library?
- Version of Support library?
- What kind of internet connection? Wifi? or 4g?
- How are you initializing the library? Are you sending any parameter?

Many thanks!

**Comment by RegisSaffi** [comment]
Hey sir,
The version of library i am using is 5.0.0
Version of play services is 16.0.0
Version of support library is 16.1.0
Connection is either WIFI or cellular ,
I have initialized the library correctly
Device i am using for test is TECNO spark k7 with android 7.0


The issue: When i open location picker activity without internet connection, it lags and cause the whole system to lag until i make "force stop" or switch off internet.
When internet is switched off, it work well(using cached data i think)

When i open it without internet connection, it work well and use cached data perfectly.
Problem is when internet is ON, either WIFI or cellular data connection

**Comment by ferranpons** [comment]
@RegisSaffi let me check it. Thanks for the info!
