### ISSUE TITLE
Now Google Places api

### ISSUE THREAD

**Issue by giaur500** [AdevintaSpain/Leku#216]
Google announced new Places Api and old api will be shut down:  https://developers.google.com/places/android-sdk/client-migration

As new api is different, you also need to update. Any plans on that? And, if I don'w want places api (only location/street name), will I still able to use your library?

**Comment by ahmedjamshedlead** [comment]
yup got the same email from Google too!

**Comment by giaur500** [comment]
Hm so what next? Will I still able to use Leku?

**Comment by ferranpons** [comment]
I'm going to migrate to the latest version so you will still able to use the library. 😉 

I'll keep you updated

**Comment by ferranpons** [comment]
PR #218 and #219 will solve this 😉

**Comment by ferranpons** [comment]
We have released a new version (v5.1.3) that use the new Places SDK compat library. The idea is to use the new Places API any time in the future but for now we are covered. 😉

**Comment by ferranpons** [comment]
Closing as Solved
