### ISSUE TITLE
Reference added, library unable to be used

### ISSUE THREAD

**Issue by giaur500** [AdevintaSpain/Leku#217]
Latest Android Studio 3.3. I added library to build.gradle and I am unable to use it:

com.schibstedspain.leku.LocationPickerActivity is unresolved in AndroidManifest. Project is Java, AndroidX. Any thoughts?

**Comment by ferranpons** [comment]
Hi @giaur500,

We had problems uploading the artifacts to bintray so let me check!


Thanks for reporting!

**Comment by ferranpons** [comment]
PR #218 and #219 will solve this :)

**Comment by MathSSDev** [comment]
I had the same issue. Any news?

**Comment by dhruvdangi** [comment]
+1

**Comment by ferranpons** [comment]
We are still looking into it. Sorry for the delay.

**Comment by achalkias** [comment]
+1

**Comment by ferranpons** [comment]
@giaur500 @MathSSDev @dhruvdangi @achalkias 

We have released a new version that should solve this issue. Please download the version 5.1.3.

Sorry for the inconvenience

**Comment by achalkias** [comment]
I get this error now 
Merging Errors: line 15 Error: Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from AndroidManifest.xml:22:18-91 is also present at AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory). Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:23:5-118:19 to override. app main manifest (this file), line 21

**Comment by ferranpons** [comment]
@achalkias are you using androidx in your project? Because it looks like you are using the support library instead.

**Comment by achalkias** [comment]
No sir i dont

**Comment by ferranpons** [comment]
The change is focused on androidx. It's my fault not changing the version instead of the patch version. I was not sure if the package was correctly uploaded to bintray

**Comment by achalkias** [comment]
So for someone to use the new google places api he needs to migrate to androidx?

**Comment by ferranpons** [comment]
Yes, if you would like to use the latest version. Alternatively, I think you could use the places sdk compat if you exclude the play services package like:

implementation ("com.google.android.libraries.places:places-compat:1.0.0") 
implementation ("com.schibstedspain.android:leku:5.1.3") {
	  exclude module: "play-services-places"
  }

**Comment by achalkias** [comment]
I made it work but in search it returns only results from united states
this is my code
 val locationPickerIntent = LocationPickerActivity.Builder()
                .withGeolocApiKey(getString(R.string.maps_key))
                .build(applicationContext)

How can i make it in search to return results from every search zone. I don't want to specify a search zone. I just want whatever the user types to be found in suggestions independently of where the user is located or what his phone locale is. Thank you for the support!

**Comment by ferranpons** [comment]
@achalkias I'm sorry but currently the only option right now is by specifying the search zone manually so it's not possible to "auto-assign" the local zone for every region. As a provisional solution you could try to filter the region before launching the map picker activity.

And If you need it please create a new Issue and I'll do it as soon as I can. But that feature (search zone) must be re-thought and refactored.
