### ISSUE TITLE
Remove "Unnamed Road" from address

### ISSUE THREAD

**Issue by iago-silva** [AdevintaSpain/Leku#235]
When Geocoder cannot to get a address it returns "Unnamed Road". Like this:

![53619720_370090530508286_8061593266006523904_n](https://user-images.githubusercontent.com/31210460/54310246-ad908100-45b0-11e9-9de9-10b124ccc217.png)

I suggest check if the returned address contains any "Unnamed Road" and don't add it

**Comment by ferranpons** [comment]
@iago-silva I'm not sure I should do this, by removing it will make it unclear to know if there is a road or not. If you make something with the address after picking the location I suggest you to remove it after picking it.

**Comment by iago-silva** [comment]
By have no method to rename it on picking, i'll have to download your lib and edit by my self to personal use.

"Unnamed Road" do not say so much to my users :/

**Comment by iago-silva** [comment]
Any solution? 😬

**Comment by ferranpons** [comment]
@iago-silva I'll create an option to hide this. I'll implement it as soon as I can. 😉

**Comment by ferranpons** [comment]
@iago-silva the new release version 6.2.0 that includes this change is ready for download. Hope it fit your needs. 😉

**Comment by iago-silva** [comment]
You are a fucking angel 😬 

Thanks!

**Comment by luizfp** [comment]
This issue can be closed!
