### ISSUE TITLE
Add library size to description

### ISSUE THREAD

**Issue by softmarshmallow** [AdevintaSpain/Leku#237]
Plz consider adding size of this library to description

**Comment by ferranpons** [comment]
@softmarshmallow thanks for your suggestion but please could you argument why would you find useful to add the size of the library on the description?
The AAR file of this library only sizes more or less 200KB and has a few classes. Do you think is important for the people to know about this?
Why are you asking to do this? Did you find any problem with the size of the library?

I have no intention to be rude but I need to understand the reasons for this suggestion and if there is any problem related to it.

Many thanks.
