### ISSUE TITLE
Searching not working in Latvia

### ISSUE THREAD

**Issue by easyjoblv** [AdevintaSpain/Leku#240]
Hello,

I'm located in Latvia

`implementation('com.schibstedspain.android:leku:5.0.0') {
`

  ```
private void findPlace() {
        Intent locationPickerIntent = new LocationPickerActivity.Builder()
                .withGooglePlacesEnabled()
                //.withLocation(41.4036299, 2.1743558)
                .build(getActivity());

        startActivityForResult(locationPickerIntent, 101);
    }
```

But in app, searching for Spain, Canada & USA.

**Comment by ferranpons** [comment]
Hi @easyjoblv!

By default it will use your default locale but if it's not in the list it will fallback to one the default ones.
To be able to limit the search zone to your needs (country) you will need to add manually the country search zone rect, by using this:

`.withSearchZone(SearchZoneRect(LatLng(26.525467, -18.910366), LatLng(43.906271, 5.394197)))`

This will solve your problem.

**Comment by easyjoblv** [comment]
SearchZoneRect - not working :(

**Comment by fukemy** [comment]
why u using SearchZoneRect, not camera zoom level?
