### ISSUE TITLE
This only works with Kotlin?

### ISSUE THREAD

**Issue by imTDB** [AdevintaSpain/Leku#241]
Hi, i'm a newbie here, i want to know if i can use this library in my java app, or if this is just for Kotlin. Thanks in advance!

**Comment by ferranpons** [comment]
Hi @imTDB !

Sure! This library will work well with your Java app. Kotlin is interoperable with Java and works on the JVM too, so it will work without any problem.

If you need more help, don't hesitate and create a new issue.

Many thanks.

**Comment by achrafelo** [comment]
Try this it worked for me

 Intent locationPickerIntent = (new LocationPickerActivity.Builder())
                .withLocation(41.4036299D, 2.1743558D)
                .withGeolocApiKey("XXXXXXX")
                .shouldReturnOkOnBackPressed().withSatelliteViewHidden()
                .withGooglePlacesEnabled()
                .withGoogleTimeZoneEnabled()
                .withVoiceSearchHidden()
                .build(this);

       // locationPickerIntent.putExtra(LocationPickerActivity.UNNAMED_ROAD_VISIBILITY, false) ;
        startActivityForResult(locationPickerIntent, request_code) ;


and in onActivityResult : 

 double latitude_double = data.getDoubleExtra("latitude", 0.0D);
                double longitude_double = data.getDoubleExtra("longitude", 0.0D);
                String address = data.getStringExtra("location_address");

**Comment by achrafelo** [comment]
Try this it worked for me

```
Intent locationPickerIntent = (new LocationPickerActivity.Builder())
.withLocation(41.4036299D, 2.1743558D)
.withGeolocApiKey("XXXXXXX")
.shouldReturnOkOnBackPressed().withSatelliteViewHidden()
.withGooglePlacesEnabled()
.withGoogleTimeZoneEnabled()
.withVoiceSearchHidden()
.build(this);
```

 
    startActivityForResult(locationPickerIntent, request_code) ;
and in onActivityResult :

```
double latitude_double = data.getDoubleExtra("latitude", 0.0D);
double longitude_double = data.getDoubleExtra("longitude", 0.0D);
String address = data.getStringExtra("location_address");
```

**Comment by ferranpons** [comment]
Closing as Solved
