### ISSUE TITLE
Add blue dot indicating your current location

### ISSUE THREAD

**Issue by AndroidGecko** [AdevintaSpain/Leku#248]
**Is your feature request related to a problem? Please describe.**
When showing the location picker with a pre-selected location using wtihLocation(LatLng), I would like to show additionally a blue dot to indicate my current location.

**Describe the solution you'd like**
a simple method like withCurrentLocation() which would enable blue dot on the map as in google maps.

**Describe alternatives you've considered**
no alternatives currently

**Comment by ferranpons** [comment]
Hi @AndroidGecko !

I'll try to implement it as soon as possible. Thanks for your suggestion.

**Comment by ferranpons** [comment]
This feature is already done on the latest version
