### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/LocationListener;

### ISSUE THREAD

**Issue by ranaprathap2** [AdevintaSpain/Leku#249]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Info Required**
- Which version of the library do you actually use?

- Do you have the localization permission granted?

- Are you sending parameters to the activity through the bundle?

- Android monitor shows any log related to the library when the error is shown?

- Any other thing that could help me to reproduce the error?

**Screenshots**

**Smartphone:**
 - Device: [e.g. Samsung S8]

**Additional context**

**Comment by ferranpons** [comment]
@ranaprathap2 Please could you send more info about your issue? Try to fill the questions of the issue template it would give me more context about the problem and maybe I could reproduce it. Thanks
