### ISSUE TITLE
Search not updating time zone

### ISSUE THREAD

**Issue by AnwarissaA** [AdevintaSpain/Leku#250]
## Description
When using search to lookup a place time zone does not updated to current selected location. It keeps the last fetched time zone. However if user clicks the map, then both location and time zone are updated.
## Info Required

- Which version of the library do you actually use? latest

- Do you have the localization permission granted?

- Are you sending parameters to the activity through the bundle?

- Could you describe what are the actions do you make to raise that error?

- Android monitor shows any log related to the library when the error is shown?

- Any other thing that could help me to reproduce the error?

**Comment by ferranpons** [comment]
Hi @AnwarissaA,

I'll try to reproduce it and solve it. Thanks for reporting this issue. :)

**Comment by ferranpons** [comment]
Should be solved on the latest version
