### ISSUE TITLE
With the google places sdk update Will Leku have problems after 29 July? 

### ISSUE THREAD

**Issue by achrafelo** [AdevintaSpain/Leku#251]
With the google places sdk update Will Leku have problems after 29 July?

**Comment by ferranpons** [comment]
Hi @achrafelo,

If you use the latest version of the library it should not have any issue related to the deprecation of the old Places SDK. Now it's using the compatibility library, it will be fully migrated to the latest version but It will work after the shut down. So you don't have to worry about it. 😉

**Comment by wisnugautama** [comment]
hi . @ferranpons ,
i've enabled the .withGooglePlacesEnabled() and setup the manifest, why the the autocomplete search is not working ? 
thanks :)

**Comment by ferranpons** [comment]
The latest version have the latest Places SDK version. (v7.0.0)
