### ISSUE TITLE
Confirm Selected Location

### ISSUE THREAD

**Issue by KelvinPac** [AdevintaSpain/Leku#253]
**Confirm selected location**
Is there a way to override any methods in the library so that I can show a location confirmation dialogue with maybe the address or location selected when the FAB is clicked in the same location picker activity?

**Comment by ferranpons** [comment]
Hi @KelvinPac 

You could try to create your own activity that extends the LocationPickerActivity and override the event of the FAB button.
Maybe in the future I redesign the library to be more flexible and allow this kind of things in an easy way.
