### ISSUE TITLE
Map return very long address

### ISSUE THREAD

**Issue by easyjoblv** [AdevintaSpain/Leku#254]
**Describe the bug**
When I select address, it will be shown + saved in DB like this:
Area, Street, Region, City, Country Code, Country Name

**To Reproduce**
N/A
**Expected behavior**
How can I maintain those strings? I need to show only Street + Country.

**Info Required**
- Which version of the library do you actually use?
    implementation("com.schibstedspain.android:leku:5.0.0") {

- Do you have the localization permission granted?

- Are you sending parameters to the activity through the bundle?

- Android monitor shows any log related to the library when the error is shown?

- Any other thing that could help me to reproduce the error?

**Screenshots**
https://paste.ofcode.org/B9AuwY5AgXn7YCzrWisxCh
**Smartphone:**
 - Device: All

**Additional context**

**Comment by ferranpons** [comment]
Hi @easyjoblv 

You actually could hide the Street and the City. If you need more fields to be hidden I'll create the option.
