### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.places.Places"

### ISSUE THREAD

**Issue by IbrahimMAATKI** [AdevintaSpain/Leku#260]
My gradle file :

```
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

apply plugin: 'kotlin-kapt'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.0"
    defaultConfig {

        minSdkVersion 17
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
        dexOptions {
            javaMaxHeapSize "4g"
        }


    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    dataBinding {
        enabled = true
    }
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
    dexOptions {
        javaMaxHeapSize "4g"
        preDexLibraries true
        dexInProcess = true
    }
    aaptOptions {
        additionalParameters "--no-version-vectors"
    }
    productFlavors {
    }
}

kapt {
    generateStubs = true
    correctErrorTypes = true
}

sourceSets {
    main {
        java {
            srcDir "${buildDir}/generated/source/kapt/main"
        }
    }
    test {
        java {
            srcDir 'src/test/java'
        }
    }
}

dependencies {

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.1.0-beta01'
    implementation 'androidx.vectordrawable:vectordrawable:1.1.0-beta02'
    implementation 'androidx.core:core-ktx:1.2.0-alpha02'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0-alpha06'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-beta2'
    implementation 'com.android.support:multidex:1.0.3'

    // --> additional
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0-alpha02'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0-alpha02'
    kapt 'com.android.databinding:compiler:3.2.0-alpha10'
    kapt 'android.arch.lifecycle:compiler:1.1.1'
    implementation 'com.intuit.sdp:sdp-android:1.0.6'
    implementation 'com.intuit.ssp:ssp-android:1.0.6'
    implementation 'com.hbb20:ccp:2.2.9'
    implementation 'com.github.bumptech.glide:glide:4.9.0'
    kapt 'com.github.bumptech.glide:compiler:4.9.0'
    implementation 'com.nex3z:flow-layout:1.2.4'
    implementation 'com.github.smarteist:autoimageslider:1.3.2'
    implementation ('com.schibstedspain.android:leku:6.2.1') {
        exclude group: 'com.google.android.gms'
        exclude group: 'androidx.appcompat'
        exclude group: 'com.google.android.libraries.places'
    }
    // additional <---

    // --> google
    implementation 'com.google.android.material:material:1.1.0-alpha07'
    implementation 'com.google.android.gms:play-services-location:17.0.0'
    implementation 'com.google.android.gms:play-services-maps:17.0.0'
    implementation 'com.google.android.libraries.places:places:1.1.0'
    implementation 'com.google.firebase:firebase-core:17.0.0'
    implementation 'com.google.firebase:firebase-messaging:19.0.1'
    implementation 'com.google.firebase:firebase-crash:16.2.1'
    // google <---

    // ----> networking
    implementation 'com.squareup.retrofit2:retrofit:2.6.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.6.0'
    implementation 'com.jakewharton.retrofit:retrofit2-rxjava2-adapter:1.0.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.12.1'
    implementation 'io.reactivex.rxjava2:rxjava:2.2.10'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation 'com.patloew.rxlocation:rxlocation:1.0.5'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.9.9'
    // networking <----


    testImplementation 'junit:junit:4.13-beta-3'
    androidTestImplementation 'androidx.test:runner:1.3.0-alpha01'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0-alpha01'
}

```
The exception that I get when I start the activity 
=====>
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/places/Places;
	at com.schibstedspain.leku.LocationPickerActivity.setUpMainVariables(LocationPickerActivity.kt:247)
	at com.schibstedspain.leku.LocationPickerActivity.onCreate(LocationPickerActivity.kt:223)
	at android.app.Activity.performCreate(Activity.java:7327)
	at android.app.Activity.performCreate(Activity.java:7318)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3095)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3258)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7058)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.places.Places" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.zedney.camion-9EdOIV7ni19NY6IuKDzLDw==/base.apk"],nativeLibraryDirectories=[/data/app/com.zedney.camion-9EdOIV7ni19NY6IuKDzLDw==/lib/arm64, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 17 more

```

**Comment by ferranpons** [comment]
Hi @IbrahimMAATKI 

Please could you send me more info about your build.gradle settings? The file you posted hasn't got any useful info.
Many thanks in advance!

**Comment by IbrahimMAATKI** [comment]
Hi @ferranpons I've updated the file

**Comment by usamabutt4756** [comment]
Hi @ferranpons i have this same issue also i need to integrate google auto places seperately in the activity but issue with depenecies . please have a look at this


apply plugin: 'com.android.application'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-android'
apply plugin: 'io.fabric'
apply plugin: 'com.google.firebase.firebase-perf'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.1"
    defaultConfig {
        applicationId "com.itsolution.wbmpakistan"
        minSdkVersion 19
        targetSdkVersion 29
        versionCode 1
        multiDexEnabled true
        versionName "1.0"
        vectorDrawables.useSupportLibrary = true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = 1.8
        targetCompatibility = 1.8
    }
}
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    /*implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'*/
    implementation 'com.android.support:appcompat-v7:29.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.github.bumptech.glide:glide:4.9.0'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:cardview-v7:29.0.0'
    implementation 'com.android.support:recyclerview-v7:29.0.0'
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation 'com.squareup.retrofit2:retrofit:2.5.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.4.0'
    implementation 'com.squareup.okhttp3:okhttp:3.12.1'
    implementation 'com.kaopiz:kprogresshud:1.1.0'
    implementation 'com.android.support:design:29.0.0'

    implementation 'com.infideap.drawerbehavior:drawer-behavior:0.1.5'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.8.0'

    implementation 'com.ss.bannerslider:bannerslider:2.0.0'
    implementation 'com.github.bachors:Android-Prefix-Input:1.1'
    implementation 'com.chaos.view:pinview:1.4.2'
    implementation 'com.google.firebase:firebase-analytics:17.3.0'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'
    implementation 'com.google.firebase:firebase-perf:19.0.6'

    //fbLogin with audience network for ads integration
    implementation 'com.facebook.android:facebook-android-sdk:4.38.1'
    implementation 'com.facebook.android:facebook-login:4.41.0'
    implementation 'com.facebook.android:audience-network-sdk:5.1.0'

    //google api using  firebase
    implementation 'com.google.android.gms:play-services-auth:18.0.0'

    // firebase mobile number logIn
    implementation 'com.google.firebase:firebase-auth:19.3.0'
    implementation 'com.google.firebase:firebase-core:17.3.0'

    //firebase push notification
    implementation 'com.google.firebase:firebase-messaging:20.1.5'

    //Room Database
    implementation 'android.arch.persistence.room:runtime:1.1.1'
    implementation 'com.facebook.stetho:stetho:1.5.1'
    implementation 'com.facebook.stetho:stetho-okhttp3:1.5.1'
    annotationProcessor 'android.arch.persistence.room:compiler:1.1.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'

//    Slider
    implementation 'com.github.smarteist:autoimageslider:1.3.2'
    implementation 'com.github.smarteist:autoimageslider:1.3.2-appcompat'

//  google login
    implementation 'com.github.mukeshsolanki:country-picker-android:1.2.4'
    implementation 'com.github.d-max:spots-dialog:1.1@aar'
    implementation 'com.android.volley:volley:1.1.1'

    implementation 'com.paypal.sdk:paypal-android-sdk:2.16.0'
    implementation 'com.heartlandpaymentsystems:globalpayments-sdk:6.1.18'
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation "android.arch.persistence.room:runtime:1.1.1"
    annotationProcessor "android.arch.persistence.room:compiler:1.1.1"
    testImplementation "android.arch.persistence.room:testing:1.1.1"
    implementation 'de.hdodenhof:circleimageview:3.0.1'
    implementation 'com.github.TutorialsAndroid:KAlertDialog:v4.1'
    implementation 'com.github.TecOrb-Developers:SmartAlertDialog:v1.0'
    implementation 'com.github.f0ris.sweetalert:library:1.5.6'

    implementation 'com.veinhorn.tagview:library:1.0.4'
    implementation 'com.braintreepayments:card-form:3.1.1'
    implementation project(path: ':rxp-hpp-android')
    implementation 'com.jaredrummler:material-spinner:1.3.1'
    implementation 'com.cepheuen.elegant-number-button:lib:1.0.3'
    implementation 'com.bestsoft32.tayyab:tt-fancy-gif-dialog:1.0.2'
    implementation 'com.github.viethoa:customdialogs:3.0.0'
    implementation 'me.relex:circleindicator:1.2.2@aar'
    implementation 'com.wdullaer:materialdatetimepicker:4.2.3'
    implementation 'com.stepstone.apprating:app-rating:2.3.1'
    implementation "com.karumi:dexter:5.0.0"
    implementation 'com.github.yalantis:ucrop:2.2.2'
    implementation 'com.github.Inconnu08:android-ratingreviews:1.2.0'
    implementation 'com.github.f0ris.sweetalert:library:1.5.1'
    implementation 'com.github.chrisbanes:PhotoView:2.1.3'
    implementation 'me.biubiubiu.justifytext:library:1.1'

    implementation 'com.sucho:placepicker:1.1.1'

    implementation 'com.google.android.material:material:1.1.0'
    implementation 'com.google.android.libraries.places:places:2.2.0'

    configurations {
        cleanedAnnotations
        compile.exclude group: 'org.jetbrains', module: 'annotations'
    }
    repositories {
        mavenCentral()
    }
    implementation "androidx.core:core-ktx:+"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.1.0"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.android.gms:play-services-maps:17.0.0'
//    implementation("com.google.android.libraries.places:places-compat:2.2.0")
    implementation("com.schibstedspain.android:leku:5.0.0") {
        exclude group: 'com.google.android.gms'
        exclude module: "play-services-places"
        exclude group: 'androidx.appcompat'

    }
    configurations.all {
        // this is a workaround for the issue:
        // https://stackoverflow.com/questions/52521302/how-to-solve-program-type-already-present-com-google-common-util-concurrent-lis
        exclude group: 'com.google.guava', module: 'listenablefuture'
    }
}
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.android.application'
repositories {
    mavenCentral()
}

**Comment by ferranpons** [comment]
It should be solved with the latest version of the library (v7.0.0)
