### ISSUE TITLE
android error Duplicate class com.google.android.libraries.places.api.internal.impl.net.pablo.AutocompletePredictionResult found in modules classes.jar

### ISSUE THREAD

**Issue by d3x773r** [AdevintaSpain/Leku#263]
I tired to remove **implementation 'com.google.android.gms:play-services-vision:18.0.0'** but the error persists and this error show up **Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules guava-23.5-android.jar (com.google.guava:guava:23.5-android) and listenablefuture-1.0.jar (com.google.guava:listenablefuture:1.0)** error

**Comment by ferranpons** [comment]
Hi @d3x773r !

This error is related to the fact that one fo the libraries is also using guava. Probably due to a transitive dependency. You would need to check the dependencies and exclude guava from them like this:

```
implementation ("androidx.legacy:legacy-support-v4:$supportLibVersion") {
    exclude group: 'com.google.guava'
}
```
