### ISSUE TITLE
FAB Theming

### ISSUE THREAD

**Issue by tefracky** [AdevintaSpain/Leku#267]
Hello,

how can I change the color of the FABs to the default App-colors like colorPrimary/colorAccent?

**Comment by w201** [comment]
I would like to reopen this discussion because not all colors could be changing by app scheme.
Also app scheme could be different than picker needs.
So how about add some full scheming or move these colors to app level
```android:tint="?colorPrimary"
        app:backgroundTint="@color/leku_white"
        app:rippleColor="@color/leku_soft_grey"
        tools:background="@color/leku_white"

**Comment by ferranpons** [comment]
It's using compose on the latest version
