### ISSUE TITLE
Data binding not working

### ISSUE THREAD

**Issue by icelic** [AdevintaSpain/Leku#268]
**Describe the bug**
I am using data binding in my app and since I included: 
```
implementation ('com.schibstedspain.android:leku:6.3.0') {
        exclude group: 'com.google.android.gms'
        exclude group: 'androidx.appcompat'
    }
```

I get the following errors on build:

> error: cannot find symbol class SwipeRefreshLayout

I am using swipe layout from androidx library and it seems like it can't recognize it.

**To Reproduce**
Include Leku library with the mentioned implementations in the app that uses androidx swiperefreshlayout

**Expected behavior**
Build should pass.

**Info Required**
- Which version of the library do you actually use?
6.3.0
- Do you have the localization permission granted?
Yes
- Are you sending parameters to the activity through the bundle?
Yes but I think this is irrelevant
- Android monitor shows any log related to the library when the error is shown?
It shows logs related to my app, ie. main activity that uses data binding
- Any other thing that could help me to reproduce the error?

**Screenshots**

**Smartphone:**
 - Device: [e.g. Samsung S8]
Oneplus 3T running android 9

**Additional context**

**Comment by icelic** [comment]
Yeah it seems a little bit odd  but whenever I remove this library everything works fine and when i add it again, error shows. It's weird. I tried excluding swiperefreshlayout but I am using it in other activities.

**Comment by dikhawk** [comment]
i have same problem

**Comment by ferranpons** [comment]
Try the latest version 7.0.0
