### ISSUE TITLE
Is there a way to take snapshot?

### ISSUE THREAD

**Issue by hanihashemi** [AdevintaSpain/Leku#272]
It would be awesome if we get a snapshot after picking a location. As I know Google Map already supports this feature and we only need to return it in the onActivityResult method.

**The solution that I like**
Get a bitmap file in `onActivityResult` method.

**Comment by ferranpons** [comment]
Hi @hanihashemi 

Thanks for your suggestion. I'll implement it as soon as I can. 😉

**Comment by ferranpons** [comment]
For this you can use the Google Maps SDK feature to take a picture from the location picked
