### ISSUE TITLE
Fatal Exception: io.reactivex.exceptions.UndeliverableException

### ISSUE THREAD

**Issue by JpegDev** [AdevintaSpain/Leku#277]
Fatal Exception: io.reactivex.exceptions.UndeliverableException
The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | HTTP error code: 400

**To Reproduce**
Go in an elevator or somewhere there is no enough network. And you will have a crash when opening location Picker.

**Info Required**
- Which version of the library do you actually use?
6.3.0

- Do you have the localization permission granted?
Yes

- Are you sending parameters to the activity through the bundle?
No

- Android monitor shows any log related to the library when the error is shown?

**Fabric stacktrace**

<img width="1241" alt="Capture d’écran 2019-10-09 à 10 33 33" src="https://user-images.githubusercontent.com/7314817/66464978-4a9c9500-ea80-11e9-98b6-6f38aca552d0.png">

Caused by com.schibstedspain.leku.geocoder.api.NetworkExceptionHTTP error code: 400 Raw Text
--
  | com.schibstedspain.leku.geocoder.api.NetworkClient.requestFromLocationName + 30 (NetworkClient.kt:30)
  | com.schibstedspain.leku.geocoder.GoogleGeocoderDataSource$getFromLocationName$1.subscribe + 33 (GoogleGeocoderDataSource.kt:33)
  | io.reactivex.d.e.b.b.b + 40 (ObservableCreate.java:40)
  | io.reactivex.f.a + 12090 (Observable.java:12090)
  | io.reactivex.d.e.b.m$a.onError + 105 (ObservableOnErrorNext.java:105)
  | io.reactivex.d.e.b.p$a.onError + 79 (ObservableRetryPredicate.java:79)
  | io.reactivex.d.e.b.r$a.onError + 63 (ObservableSubscribeOn.java:63)
  | io.reactivex.d.e.b.b$a.b + 84 (ObservableCreate.java:84)
  | com.schibstedspain.leku.geocoder.AndroidGeocoderDataSource$getFromLocationName$1.subscribe + 19 (AndroidGeocoderDataSource.kt:19)
  | io.reactivex.d.e.b.b.b + 40 (ObservableCreate.java:40)
  | io.reactivex.f.a + 12090 (Observable.java:12090)
  | io.reactivex.d.e.b.r$b.run + 96 (ObservableSubscribeOn.java:96)
  | io.reactivex.l$a.run + 578 (Scheduler.java:578)
  | io.reactivex.d.g.h.run + 66 (ScheduledRunnable.java:66)
  | io.reactivex.d.g.h.call + 57 (ScheduledRunnable.java:57)
  | java.util.concurrent.FutureTask.run + 237 (FutureTask.java:237)
  | java.lang.Thread.run + 776 (Thread.java:776)

**Smartphone:**
 - Device: Sony Xperia XZ2 compact, Huawei Mate 8, Lenovo K3 Note, Samsung Galaxy J3(2016)

**Comment by ferranpons** [comment]
Hi @JpegDev 

I'm looking into it. Many thanks for reporting the issue.

**Comment by ferranpons** [comment]
Solved in the latest version 7.0.0
