### ISSUE TITLE
Places suggestion not working properly

### ISSUE THREAD

**Issue by grabcityinfo** [AdevintaSpain/Leku#278]
Places suggestion box is not working properly. 

The dropdown shows one place only at a time.

Could you please provide a way of applying "Custom Places Autocomplete Adapter" to your "search box"?

**Comment by Harshit31** [comment]
Hey, I'm having the same problem. Can someone tell me how can I search for all the places in the world using the given search bar? 

Right now it doesn't return the correct data in suggestion when searching for a particular place.

**Comment by ferranpons** [comment]
Hi @grabcityinfo @Harshit31 

If you don't set a "Locale" for Leku then it tries to search all over the world, the problem is that could not return accurate data. Also, the default geocoder that retrieves the information is very limited.

About giving the option to provide a custom auto-complete adapter I'll consider it and make it available in future versions.

Sorry for the inconvenience.

**Comment by grabcityinfo** [comment]
> Hi @grabcityinfo @Harshit31
> 
> If you don't set a "Locale" for Leku then it tries to search all over the world, the problem is that could not return accurate data. Also, the default geocoder that retrieves the information is very limited.
> 
> About giving the option to provide a custom auto-complete adapter I'll consider it and make it available in future versions.
> 
> Sorry for the inconvenience.

That's great.
I'm waiting for such feature.
Thanks for great solution,

**Comment by grabcityinfo** [comment]
> Hi @grabcityinfo @Harshit31
> 
> If you don't set a "Locale" for Leku then it tries to search all over the world, the problem is that could not return accurate data. Also, the default geocoder that retrieves the information is very limited.
> 
> About giving the option to provide a custom auto-complete adapter I'll consider it and make it available in future versions.
> 
> Sorry for the inconvenience.

Hi @ferranpons 
Currently I'm using this [ADAPTER ](https://github.com/googlearchive/android-play-places/blob/master/PlaceCompleteAdapter/Application/src/main/java/com/example/google/playservices/placecomplete/PlaceAutocompleteAdapter.java) with any AutocompleteTextView. It works very well and more place suggestions are shown on UI. But the PickerLocation you share shared shows one suggestion only. I did not find out why it behaves that way.

Please, fix it. We are anxiously waiting for your update.

Cheers

**Comment by Harshit31** [comment]
@grabcityinfo Can you share the code for your adapter implementation. It'll be really helpful for me.

**Comment by ferranpons** [comment]
It should be solved on the latest version
