### ISSUE TITLE
BUG!!!

### ISSUE THREAD

**Issue by ViTech2019** [AdevintaSpain/Leku#279]
** lateinit property timeZone has not been initialized when returning from maps activity**

**To Reproduce**
set the following intent:
            val locationPickerIntent = LocationPickerActivity.Builder()
                .withLocation(32.028320, 34.781879)
                .withGeolocApiKey("GEOLOCKEY")
//                .withSearchZone("es_ES")
//                .withSearchZone(SearchZoneRect(LatLng(26.525467, -18.910366), LatLng(43.906271, 5.394197)))
//                .withDefaultLocaleSearchZone()
                .shouldReturnOkOnBackPressed()
                .withStreetHidden()
//                .withCityHidden()
                .withZipCodeHidden()
                .withSatelliteViewHidden()
                .withGooglePlacesEnabled()
                .withGoogleTimeZoneEnabled()
                .withVoiceSearchHidden()
//                .withUnnamedRoadHidden()
                .build(context!!)

called from fragment

**Should return required info**

**Info Required**
- Which version of the library do you actually use? - 5.0.0

- Do you have the localization permission granted?

- Are you sending parameters to the activity through the bundle?

- Android monitor shows any log related to the library when the error is shown?

- Any other thing that could help me to reproduce the error?

**Screenshots**

**Smartphone:**
 - Device: [e.g. Samsung S8]

**Additional context**

**Comment by ferranpons** [comment]
Hi @ViTech2019 

I'll review it and solve the problem. Thanks for reporting it.

**Comment by ferranpons** [comment]
@ViTech2019 Please update to the latest version of the library (6.3.0) you're using a buggy old version
