### ISSUE TITLE
Cannot invoke method get() on null object

### ISSUE THREAD

**Issue by inforaamitsolutions** [AdevintaSpain/Leku#288]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ferranpons** [comment]
Hi @inforaamitsolutions 

It's difficult for me to know what is crashing if you don't provide more info about the issue. Please could you send me the stack trace or more info about how to reproduce it? Thanks.
