### ISSUE TITLE
Picker activity is opening very slowly.

### ISSUE THREAD

**Issue by mohdaquib** [AdevintaSpain/Leku#295]
When I am opening Picker activity from my app activity passing current latitude and longitude, it is taking time to open and not happening instant.

It should be instant or there should be some kind of threading mechanism or callbacks.

- Which version of the library do you actually use?
6.4.0

- Do you have the localization permission granted?

- Are you sending parameters to the activity through the bundle?
No

- Android monitor shows any log related to the library when the error is shown?
No

- Any other thing that could help me to reproduce the error?

Recording Url - 
https://vimeo.com/407486865

Smartphone- 
 - Asus Zenphone Max Pro

**Comment by ferranpons** [comment]
Should be solved on the latest version
