### ISSUE TITLE
Crash leku 7.1.0

### ISSUE THREAD

**Issue by JpegDev** [AdevintaSpain/Leku#304]
**Describe the bug**
I have a kotlin Null pointer exception when I start the locationPickerActiity
Caused by: kotlin.KotlinNullPointerException
        at com.schibstedspain.leku.LocationPickerActivity.getTransitionBundleParams(LocationPickerActivity.kt:967)

**To Reproduce**
Just launch activity, the crash occured in: 
updateValuesFromBundle(savedInstanceState)-> getTransitionBundleParams()->
 if (transitionBundle.keySet().contains(GEOLOC_API_KEY)) {
           apiInteractor!!.setApiKey(transitionBundle.getString(GEOLOC_API_KEY, ""))
 }
Apparently apiInteractor is null at this moment, because it's initialized in:
setUpMainVariables:

| updateValuesFromBundle(savedInstanceState)
| setUpContentView()
V setUpMainVariables()

 Intent locationPickerIntent = (new LocationPickerActivity.Builder())
                        .withGeolocApiKey(this.getResources().getString(R.string.google_api_key))
                        .withSearchZone("fr_FR")
                        .shouldReturnOkOnBackPressed()
                        .withZipCodeHidden()
                        .withUnnamedRoadHidden()
                        .build(this.getActivity());

api key is not null or empty

**Expected behavior**
No crash

**Info Required**
- Which version of the library do you actually use?
7.1.0

- Do you have the localization permission granted?
Yes

- Are you sending parameters to the activity through the bundle?
Just parameter with the LocationPickerActivity.Builder()

- Android monitor shows any log related to the library when the error is shown?
No

- Any other thing that could help me to reproduce the error?

**Screenshots**

**Smartphone:**
 - Emulator API 29
- Xiaomi Redmi Note 7 Android 9

**Additional context**

**Comment by aliondos** [comment]
Having same issue.

**Comment by ferranpons** [comment]
@JpegDev @aliondos I'm looking into it! I'll send you an update when I found the problem.

Thanks for reporting!

**Comment by vijeeshin** [comment]
When i paste  this meta inside manifest Application tag   <meta-data android:name="com.google.android.geo.API_KEY" android:value="Your Key"/> fixed my  problem.

**Comment by vijeeshin** [comment]
`<meta-data android:name="com.google.android.geo.API_KEY" android:value="YOUR_API_KEY"/>`  fix the problem

**Comment by vijeeshin** [comment]
`<meta-data android:name="com.google.android.geo.API_KEY" android:value="YOUR_API_KEY"/>` inside manifest application tag fixed my problem.

**Comment by jazeelmohd** [comment]
> `<meta-data android:name="com.google.android.geo.API_KEY" android:value="YOUR_API_KEY"/>` inside manifest application tag fixed my problem.

I already have it in my manifest file. Can you explain how you fixed the issue ?

**Comment by vijeeshin** [comment]
> > `<meta-data android:name="com.google.android.geo.API_KEY" android:value="YOUR_API_KEY"/>` inside manifest application tag fixed my problem.
> 
> I already have it in my manifest file. Can you explain how you fixed the issue ?

check geocoding,map,geolocation and places enabled in google api console.

**Comment by vijeeshin** [comment]
> > `<meta-data android:name="com.google.android.geo.API_KEY" android:value="YOUR_API_KEY"/>` inside manifest application tag fixed my problem.
> 
> I already have it in my manifest file. Can you explain how you fixed the issue ?
in app/build.gradle make sure that
unde defaultConfig
`multiDexEnabled true`  

and  in dependencies
` implementation ('com.schibstedspain.android:leku:7.1.0') {
        exclude group: 'com.google.android.gms'
        exclude group: 'androidx.appcompat'
    }
    implementation 'com.google.android.gms:play-services-base:17.0.0'
    implementation 'com.google.android.gms:play-services-maps:17.0.0'
    implementation 'com.google.android.gms:play-services-location:17.0.0'`

**Comment by javabbt** [comment]
same issue

**Comment by tefracky** [comment]
I modified the LocationPickerActivity.kt as followed. This works now fine for me.
`    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setUpMainVariables()
        updateValuesFromBundle(savedInstanceState)
        setUpContentView()
        setUpResultsList()
        setUpToolBar()
        checkLocationPermission()
        setUpSearchView()
        setUpMapIfNeeded()
        setUpFloatingButtons()
        buildGoogleApiClient()
        track(TrackEvents.ON_LOAD_LOCATION_PICKER)
    }`

**Comment by MiracleChen001** [comment]
Same issue. Any update about this?

**Comment by ferranpons** [comment]
Hi @JpegDev @aliondos @vijeeshin @MiracleChen001 @jazeelmohd @tefracky @javabbt 

This issue is corrected on the new version 7.2.0. 

Sorry for the inconvenience.

**Comment by ferranpons** [comment]
I'm closing the issue because is solved with the version 7.2.0
