### ISSUE TITLE
Should explain better the steps. Because its confuse. I try but don´t work.

### ISSUE THREAD

**Issue by eDR10x** [AdevintaSpain/Leku#305]
I want just to implement place picker in my app. But I follow the steps but don't work. So i download the file , adn open the app folder and leku folder. But each have differents sample for guide. I don´t know what to do.

I want to use a editText and when onclick. Open the placepicker of leku, and get the address in the edittext.

Can you guide me for this steps?.
Thanks in advanced.

**Comment by ferranpons** [comment]
On the documentation and the sample app has all the info needed to use it.
