### ISSUE TITLE
Search Box Issues

### ISSUE THREAD

**Issue by jaseelmohd** [AdevintaSpain/Leku#307]
## Description

Thanks for the great library. I have some issues with the search box.

- The search only shows 1-2 suggestions
- The search is slow, like if I enter an address with 2-3 words, the last word being the city name then the search is very slow as it flashes many times different result while finally getting the actual location
- The suggestions are confusing for the users, the suggestions just display the address, and not the full location details like name and address. Normal search in google maps or places Api can be referred for this feature.

## Info Required

- Which version of the library do you actually use? latest

- Do you have the localization permission granted? yes

- Are you sending parameters to the activity through the bundle? no

- Could you describe what are the actions do you make to raise that error?

- Android monitor shows any log related to the library when the error is shown?

- Any other thing that could help me to reproduce the error?

## Screenshots
Issue 2
![leku_issue](https://user-images.githubusercontent.com/23740454/86088227-86223800-bac3-11ea-9e56-78b3a8dfd768.gif)

Issue 3
How I want it the search to be displayed, this will be easier for my users.
![image](https://user-images.githubusercontent.com/23740454/86087544-1cedf500-bac2-11ea-8bf2-1b67a858bbd8.png)
How it is displayed in Leku
![image](https://user-images.githubusercontent.com/23740454/86087651-54f53800-bac2-11ea-82d1-bacd33e34f35.png)

Please look into these issues and provide a solution. Please let me know whether I am doing anything wrong if that is the case

**Comment by kareller** [comment]
I have same problem. Is there any fix?

**Comment by mala9974025544** [comment]
I am having the same issues its only shows 1 suggestion instead of five which is default given by google autocomplete view

**Comment by Sagar130798** [comment]
Please provide the real-time google places autocomplete search instead of customize it

**Comment by ferranpons** [comment]
This is solved. And the places suggestion is on it's way.
