### ISSUE TITLE
Search by text

### ISSUE THREAD

**Issue by MostafaGad1911** [AdevintaSpain/Leku#316]
**Not need to search by text**

**To Reproduce**
Add attribute control show/hide search edit text

**Info Required**
- Which version of the library do you actually use? Last version

- Are you sending parameters to the activity through the bundle?

- Android monitor shows any log related to the library when the error is shown?

- Any other thing that could help me to reproduce the error?

**Screenshots**

**Smartphone:**
 - Device: [e.g. Samsung S8]

**Additional context**

**Comment by ferranpons** [comment]
This feature is already implemented. Check out the latest version that includes `.withSearchBarHidden()`
