### ISSUE TITLE
.withGooglePlacesEnabled()

### ISSUE THREAD

**Issue by sondangpangrib** [AdevintaSpain/Leku#318]
Hi.. 
iget this error
cannot resolves method   .withGooglePlacesEnabled()
how to solves this ??

also move the library to mavenCentral()

jcenter will shutdown soon

Thanks for library

Sondang

**Comment by ferranpons** [comment]
It was modified, you need to provide the API Key in order to enable it. Using this:

`.withGooglePlacesApiKey("<PUT API KEY HERE>")`
