### ISSUE TITLE
Current location is not showing in latest version os

### ISSUE THREAD

**Issue by shashankbansal21** [AdevintaSpain/Leku#319]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Info Required**
- Which version of the library do you actually use?

- Do you have the localization permission granted?

- Are you sending parameters to the activity through the bundle?

- Android monitor shows any log related to the library when the error is shown?

- Any other thing that could help me to reproduce the error?

**Screenshots**

**Smartphone:**
 - Device: [e.g. Samsung S8]

**Additional context**

**Comment by RiteshJain473** [comment]
This bug also effects my app where Current Location Button wont work. All permission given, also GPS on.
Android: SDK 31
Device: Redmi Note 8
My Device OS version: Android 11

**Comment by ferranpons** [comment]
I assume this is already solved. Let me know if you're still experiencing it. Thanks!
