### ISSUE TITLE
very laggy when open map

### ISSUE THREAD

**Issue by fukemy** [AdevintaSpain/Leku#333]
Im using version 9.1.1 with Kotlin, my device is Samsung A02S. When start location picker screen, it's lag and can not touch into view, after ~5 sec, it's show my current location and i can touch the screen

```
val locationPickerIntent = LocationPickerActivity.Builder()
                                .withGeolocApiKey("KEY")
                                .withSatelliteViewHidden()
                                .build(this@ChatScreen)

                            lauchLocationPicker.launch(locationPickerIntent)
````

**Comment by ferranpons** [comment]
I close this issue because we have a newer version. If you're still experiencing this problem please let me know.

**Comment by fukemy** [comment]
do you think people will still used this lib after 2 years bug exist?
