### ISSUE TITLE
How can i filter results by country?

### ISSUE THREAD

**Issue by nmssalman** [AdevintaSpain/Leku#334]
Im currently in canada and when i search things, its suggesting items from US and other countries too. how can i limit result to a specific country?

```
LocationPickerActivity.Builder()
                .withLocation(location)
                .withGooglePlacesApiKey(context.getString(R.string.google_map_api))
                .withDefaultLocaleSearchZone()
                .shouldReturnOkOnBackPressed()
                .withGoogleTimeZoneEnabled()
                .withVoiceSearchHidden()
                .build(context)
```

**Comment by ferranpons** [comment]
You can use `.withSearchZone(SearchZoneRect(LatLng(26.525467, -18.910366), LatLng(43.906271, 5.394197)))` method to filter by country by providing the Country Rectangle locations
