### ISSUE TITLE
Fab is not positioned correctelly

### ISSUE THREAD

**Issue by fahad9022** [AdevintaSpain/Leku#46]
At first time It's good but when i move the tracker to another place 
the FAB looks like this

![screenshot 2f e2 80 8f 2f - -](https://cloud.githubusercontent.com/assets/10420072/19730316/7cae6a6c-9ba2-11e6-9f0c-589240df0abb.png)

Hope you fix it ASAP
Many Thanks. 
(Samsung Galaxy S6)

**Comment by ferranpons** [comment]
Hi @fahad9022,

Thanks for reporting this issue. I'll solve it as soon as I can. 😉 

![giphy 45](https://cloud.githubusercontent.com/assets/1225463/19757600/150ca996-9c24-11e6-91ed-60689598d315.gif)

**Comment by ferranpons** [comment]
@fahad9022 new version 2.3.1 is available for download. Please, confirm that this issue is not being reproduced anymore. Thanks!

**Comment by fahad9022** [comment]
Thanks for fast respond , I have tested it once it's good and once like this 
![screenshot 2f e2 80 8f 2f - -](https://cloud.githubusercontent.com/assets/10420072/19829710/9cbb2f2e-9df1-11e6-849a-45237578a0c0.png)

and I noticed that locate (FAB button) is't working at all
Many Thanks again.

**Comment by ferranpons** [comment]
@fahad9022 it's possible that the current location FAB button doesn't work if you haven't got the permission.

About the screenshot... please could you tell me which version of android has that device? I'll review it again.

Sorry for replying late this time. Many thanks

**Comment by fahad9022** [comment]
It's OK, I have Android 6.0.1 (M)

**Comment by ferranpons** [comment]
@fahad9022 I cannot reproduce the issue with my device in RTL mode. I'm also testing it in a Samsung S6 with the same android version in RTL mode. Weird thing. :S

If you find the solution, please submit a PR. Sorry about that.
